<?php

namespace Database\Seeders\Admin;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $products = [
            // Tech Haven
            [
                'store_id' => 1,
                'brand_id' => 1, // Apple
                'product_type' => 'physical',
                'name' => 'Apple MacBook Air M2 13-inch',
                'slug' => Str::slug('Apple MacBook Air M2 13-inch'),
                'price' => 18990000,
                'special_price' => 17990000,
                'special_price_start' => Carbon::now()->subDays(3),
                'special_price_end' => Carbon::now()->addDays(5),
                'description' => 'The Apple MacBook Air M2 13-inch offers exceptional performance with Apple Silicon, lightweight design, and all-day battery life. Perfect for professionals and students alike.',
                'short_description' => 'Ultra-light laptop powered by Apple M2 chip with amazing speed and battery life.',
                'sku' => 'MBA13M2',
                'manage_stock' => 1,
                'qty' => 25,
                'in_stock' => true,
                'viewed' => 120,
                'status' => 'active',
                'approved_status' => 'approved',
                'is_featured' => true,
                'is_hot' => true,
                'is_new' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'store_id' => 1,
                'brand_id' => 3, // Sony
                'product_type' => 'physical',
                'name' => 'Sony WH-1000XM5 Wireless Headphones',
                'slug' => Str::slug('Sony WH-1000XM5 Wireless Headphones'),
                'price' => 5499000,
                'special_price' => 4999000,
                'special_price_start' => Carbon::now()->subDays(2),
                'special_price_end' => Carbon::now()->addDays(3),
                'description' => 'Industry-leading noise-canceling wireless headphones with crystal-clear sound, 30-hour battery life, and adaptive noise control for superior audio experience.',
                'short_description' => 'Premium wireless noise-canceling headphones for immersive sound.',
                'sku' => 'SONYWH1000XM5',
                'manage_stock' => 1,
                'qty' => 40,
                'in_stock' => true,
                'viewed' => 80,
                'status' => 'active',
                'approved_status' => 'approved',
                'is_featured' => true,
                'is_hot' => false,
                'is_new' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Gadget World
            [
                'store_id' => 2,
                'brand_id' => 2, // Samsung
                'product_type' => 'physical',
                'name' => 'Samsung Galaxy S24 Ultra 5G',
                'slug' => Str::slug('Samsung Galaxy S24 Ultra 5G'),
                'price' => 20999000,
                'special_price' => 19999000,
                'special_price_start' => Carbon::now()->subDays(1),
                'special_price_end' => Carbon::now()->addDays(7),
                'description' => 'The Samsung Galaxy S24 Ultra redefines smartphone performance with a 200MP camera, 120Hz AMOLED display, and Snapdragon 8 Gen 3 processor.',
                'short_description' => 'Flagship smartphone with 200MP camera and powerful Snapdragon processor.',
                'sku' => 'SGS24U',
                'manage_stock' => 1,
                'qty' => 35,
                'in_stock' => true,
                'viewed' => 250,
                'status' => 'active',
                'approved_status' => 'approved',
                'is_featured' => true,
                'is_hot' => true,
                'is_new' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'store_id' => 2,
                'brand_id' => 5, // Oppo
                'product_type' => 'physical',
                'name' => 'Oppo Reno10 Pro+ 5G',
                'slug' => Str::slug('Oppo Reno10 Pro+ 5G'),
                'price' => 9999000,
                'special_price' => 8999000,
                'special_price_start' => Carbon::now()->subDays(5),
                'special_price_end' => Carbon::now()->addDays(2),
                'description' => 'The Oppo Reno10 Pro+ 5G combines elegant design with a flagship-level camera system, long battery life, and fast charging.',
                'short_description' => 'Stylish 5G smartphone with advanced camera and fast charging.',
                'sku' => 'OPR10PRO',
                'manage_stock' => 1,
                'qty' => 50,
                'in_stock' => true,
                'viewed' => 110,
                'status' => 'active',
                'approved_status' => 'approved',
                'is_featured' => false,
                'is_hot' => true,
                'is_new' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // // Smart Living Hub
            // [
            //     'store_id' => 3,
            //     'brand_id' => 4, // Xiaomi
            //     'product_type' => 'physical',
            //     'name' => 'Xiaomi Smart Air Purifier 4 Pro',
            //     'slug' => Str::slug('Xiaomi Smart Air Purifier 4 Pro'),
            //     'price' => 3999000,
            //     'special_price' => 3499000,
            //     'special_price_start' => Carbon::now()->subDays(4),
            //     'special_price_end' => Carbon::now()->addDays(6),
            //     'description' => 'Keep your home fresh with Xiaomi Smart Air Purifier 4 Pro — featuring HEPA filtration, smart app control, and whisper-quiet operation.',
            //     'short_description' => 'Smart air purifier with app control and HEPA filtration.',
            //     'sku' => 'XMAP4PRO',
            //     'manage_stock' => 1,
            //     'qty' => 70,
            //     'in_stock' => true,
            //     'viewed' => 90,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => false,
            //     'is_hot' => false,
            //     'is_new' => true,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],
            // [
            //     'store_id' => 3,
            //     'brand_id' => 7, // Asus
            //     'product_type' => 'physical',
            //     'name' => 'Asus ROG Strix G16 Gaming Laptop',
            //     'slug' => Str::slug('Asus ROG Strix G16 Gaming Laptop'),
            //     'price' => 22999000,
            //     'special_price' => 21999000,
            //     'special_price_start' => Carbon::now()->subDays(2),
            //     'special_price_end' => Carbon::now()->addDays(10),
            //     'description' => 'Asus ROG Strix G16 is a powerful gaming laptop with RTX 4070 GPU, 13th Gen Intel Core i9 processor, and immersive 165Hz display.',
            //     'short_description' => 'High-performance gaming laptop with RTX graphics.',
            //     'sku' => 'ROGSTRIXG16',
            //     'manage_stock' => 1,
            //     'qty' => 20,
            //     'in_stock' => true,
            //     'viewed' => 300,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => true,
            //     'is_hot' => true,
            //     'is_new' => false,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],

            // // Elite Electronics
            // [
            //     'store_id' => 4,
            //     'brand_id' => 9, // HP
            //     'product_type' => 'physical',
            //     'name' => 'HP Envy x360 Convertible Laptop',
            //     'slug' => Str::slug('HP Envy x360 Convertible Laptop'),
            //     'price' => 15999000,
            //     'special_price' => 14999000,
            //     'special_price_start' => Carbon::now()->subDays(7),
            //     'special_price_end' => Carbon::now()->addDays(3),
            //     'description' => 'The HP Envy x360 offers the flexibility of a tablet with the power of a laptop, featuring a 360° hinge and bright Full HD touchscreen.',
            //     'short_description' => 'Convertible laptop with touchscreen and AMD Ryzen performance.',
            //     'sku' => 'HPENVYX360',
            //     'manage_stock' => 1,
            //     'qty' => 30,
            //     'in_stock' => true,
            //     'viewed' => 75,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => false,
            //     'is_hot' => false,
            //     'is_new' => false,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],
            // [
            //     'store_id' => 4,
            //     'brand_id' => 10, // Dell
            //     'product_type' => 'physical',
            //     'name' => 'Dell XPS 15 OLED Laptop',
            //     'slug' => Str::slug('Dell XPS 15 OLED Laptop'),
            //     'price' => 28999000,
            //     'special_price' => 26999000,
            //     'special_price_start' => Carbon::now()->subDays(2),
            //     'special_price_end' => Carbon::now()->addDays(4),
            //     'description' => 'Experience stunning visuals and premium build quality with the Dell XPS 15, featuring a 3.5K OLED display and Intel Core i9 performance.',
            //     'short_description' => 'Premium laptop with OLED display and sleek aluminum body.',
            //     'sku' => 'DELLXPS15',
            //     'manage_stock' => 1,
            //     'qty' => 15,
            //     'in_stock' => true,
            //     'viewed' => 130,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => true,
            //     'is_hot' => false,
            //     'is_new' => true,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],

            // // NextGen Tech Store
            // [
            //     'store_id' => 5,
            //     'brand_id' => 1, // Apple
            //     'product_type' => 'digital',
            //     'name' => 'Apple Music Annual Subscription',
            //     'slug' => Str::slug('Apple Music Annual Subscription'),
            //     'price' => 599000,
            //     'special_price' => 499000,
            //     'special_price_start' => Carbon::now()->subDays(5),
            //     'special_price_end' => Carbon::now()->addDays(20),
            //     'description' => 'Apple Music subscription gives you unlimited access to over 100 million songs, curated playlists, and exclusive artist content.',
            //     'short_description' => 'Annual plan for Apple Music with access to all premium features.',
            //     'sku' => 'APPMUSIC12',
            //     'manage_stock' => 0,
            //     'qty' => null,
            //     'in_stock' => true,
            //     'viewed' => 60,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => false,
            //     'is_hot' => false,
            //     'is_new' => false,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],
            // [
            //     'store_id' => 5,
            //     'brand_id' => 8, // Lenovo
            //     'product_type' => 'physical',
            //     'name' => 'Lenovo Legion 7i Gaming Laptop',
            //     'slug' => Str::slug('Lenovo Legion 7i Gaming Laptop'),
            //     'price' => 25999000,
            //     'special_price' => 23999000,
            //     'special_price_start' => Carbon::now()->subDays(1),
            //     'special_price_end' => Carbon::now()->addDays(10),
            //     'description' => 'The Lenovo Legion 7i is a top-tier gaming laptop powered by Intel Core i9 and NVIDIA RTX 4080 for ultimate gaming experience.',
            //     'short_description' => 'Flagship gaming laptop with high-end specs and RGB design.',
            //     'sku' => 'LEGION7I',
            //     'manage_stock' => 1,
            //     'qty' => 18,
            //     'in_stock' => true,
            //     'viewed' => 190,
            //     'status' => 'active',
            //     'approved_status' => 'approved',
            //     'is_featured' => true,
            //     'is_hot' => true,
            //     'is_new' => false,
            //     'created_at' => $now,
            //     'updated_at' => $now,
            // ],
            // (Tambahkan sisa hingga 15 produk dengan pola sama)
        ];

        DB::table('products')->insert($products);
    }
}
